"""Add a summary header to the HTML report generated by reccmp-reccmp.

reccmp's report is a bare function listing. This rewrites it in place to add
overall match statistics, a progress bar, the report date/commit and a link
back to the repository, plus a viewport tag so it is usable on phones.
"""

import argparse
import html
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_REPO_URL = "https://github.com/Jor02/DelayLama"

# Entry types in reccmp's report data.
TYPE_FUNCTION = 1
TYPE_VTABLE = 5

REPORT_RE = re.compile(r"window\.global_reccmp_report\s*=\s*(\{.*?\});\s*</script>", re.S)

STYLE = """
    <style>
      body {
        margin: 0 16px 32px;
      }

      .summary {
        margin: 1.5em 0 2em;
      }

      .summary h1 {
        margin-bottom: 0.25em;
      }

      .summary .meta {
        color: #b0b0b0;
        font-size: 10pt;
        text-align: center;
        margin: 0 0 1.5em;
      }

      .summary a {
        color: #a0a0ff;
      }

      .stats {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 10px;
        margin-bottom: 1em;
      }

      .stat {
        background: #282828;
        border: 1px #505050 solid;
        border-radius: 0.5em;
        padding: 0.75em 1em;
      }

      .stat .value {
        font-size: 1.6em;
        font-weight: bold;
        font-variant-numeric: tabular-nums;
      }

      .stat .label {
        color: #b0b0b0;
        font-size: 10pt;
      }

      .bar {
        display: flex;
        height: 14px;
        border-radius: 7px;
        overflow: hidden;
        background: #303030;
      }

      .bar > span {
        display: block;
        height: 100%;
      }

      .legend {
        display: flex;
        flex-wrap: wrap;
        gap: 0.5em 1.5em;
        font-size: 10pt;
        margin-top: 0.5em;
      }

      .legend i {
        display: inline-block;
        width: 0.8em;
        height: 0.8em;
        border-radius: 2px;
        margin-right: 0.4em;
        vertical-align: -0.05em;
      }

      .main {
        overflow-x: auto;
      }
    </style>
"""


def effective_accuracy(entry):
    # An effective match (differs only in e.g. register allocation) counts as 100%.
    return 1.0 if entry.get("effective") else entry.get("matching", 0.0)


def compute_stats(report):
    """Mirror reccmp's own numbers (report_function_accuracy in reccmp/compare/report.py
    and the summary in reccmp/tools/asmcmp.py) so the page agrees with progress.svg."""
    data = report.get("data", [])
    # Entries without a type come from older reports and are functions.
    functions = [e for e in data if e.get("type") in (None, TYPE_FUNCTION)]
    vtables = [e for e in data if e.get("type") == TYPE_VTABLE]

    implemented = [e for e in functions if not e.get("stub")]
    perfect = sum(1 for e in implemented if e.get("matching", 0.0) >= 1.0)
    effective = sum(1 for e in implemented if e.get("effective") and e.get("matching", 0.0) < 1.0)
    score = sum(effective_accuracy(e) for e in implemented)

    # Only matched entries are serialized; function_count (reccmp >= July 2026) also
    # includes functions that could not be found in the recompiled binary.
    total = max(report.get("function_count") or 0, len(functions))

    return {
        "total": total,
        "implemented": len(implemented),
        "perfect": perfect,
        "effective": effective,
        "partial": len(implemented) - perfect - effective,
        "stubs": len(functions) - len(implemented),
        "unmatched": total - len(functions),
        "accuracy": score / len(implemented) if implemented else 0.0,
        "progress": score / total if total else 0.0,
        "vtables": len(vtables),
        "vtables_perfect": sum(1 for e in vtables if effective_accuracy(e) >= 1.0),
    }


def pct(part, whole):
    return 100.0 * part / whole if whole else 0.0


def build_summary(report, stats, repo_url, commit):
    total = stats["total"]

    meta = [html.escape(report.get("file", "")) or "Unknown binary"]
    timestamp = report.get("timestamp")
    if timestamp:
        when = datetime.fromtimestamp(timestamp, tz=timezone.utc)
        meta.append(f"Generated {when:%Y-%m-%d %H:%M} UTC")
    if commit:
        short = html.escape(commit[:7])
        meta.append(f'commit <a href="{html.escape(repo_url)}/commit/{html.escape(commit)}"><code>{short}</code></a>')
    meta.append(f'<a href="{html.escape(repo_url)}">Source on GitHub</a>')

    def tile(value, label):
        return f'<div class="stat"><div class="value">{value}</div><div class="label">{label}</div></div>'

    implemented = stats["implemented"]
    tiles = [
        tile(f'{stats["accuracy"] * 100:.2f}%', f"Accuracy (average of {implemented} implemented functions)"),
        tile(f'{stats["progress"] * 100:.2f}%', f"Progress (accuracy over all {total} functions)"),
        tile(f'{stats["perfect"]} / {total}', f'Perfect functions ({pct(stats["perfect"], total):.1f}%)'),
        tile(f'{stats["stubs"]}', "Stubs"),
    ]
    if stats["effective"]:
        tiles.insert(3, tile(stats["effective"], "Effective matches"))
    if stats["vtables"]:
        tiles.append(tile(f'{stats["vtables_perfect"]} / {stats["vtables"]}', "Matching vtables"))

    # (css class, legend name, color, count)
    segments = [
        ("perfect", "Perfect", "#80FF80", stats["perfect"]),
        ("effective", "Effective", "#8080FF", stats["effective"]),
        ("partial", "Partial", "#E0C060", stats["partial"]),
        ("stub", "Stub", "#606060", stats["stubs"]),
        ("unmatched", "Not found in recomp", "#FF8080", stats["unmatched"]),
    ]
    segments = [s for s in segments if s[3] or s[0] in ("perfect", "partial", "stub")]
    bar = "".join(
        f'<span style="width: {pct(count, total):.3f}%; background: {color}" title="{name}: {count}"></span>'
        for _, name, color, count in segments
        if count
    )
    legend = "".join(
        f'<span><i style="background: {color}"></i>{name} {count}</span>'
        for _, name, color, count in segments
    )
    bar_label = ", ".join(f"{count} {name.lower()}" for _, name, _, count in segments)

    return f"""<div class="summary">
        <h1>Delay Lama Decompilation Status</h1>
        <p class="meta">{" &middot; ".join(meta)}</p>
        <div class="stats">{"".join(tiles)}</div>
        <div class="bar" role="img" aria-label="Functions: {bar_label}">{bar}</div>
        <div class="legend">{legend}</div>
      </div>"""


def replace_once(page, old, new, what):
    if old not in page:
        print(f"warning: could not find {what} in report, skipping", file=sys.stderr)
        return page
    return page.replace(old, new, 1)


def enhance(page, repo_url, commit):
    match = REPORT_RE.search(page)
    if not match:
        raise ValueError("report data (window.global_reccmp_report) not found")
    report = json.loads(match.group(1))
    stats = compute_stats(report)

    page = replace_once(
        page,
        "<head>",
        '<head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">',
        "<head>",
    )
    page = replace_once(page, "<html>", '<html lang="en">', "<html>")
    page = replace_once(
        page,
        "<title>Decompilation Status</title>",
        "<title>Delay Lama Decompilation Status</title>",
        "<title>",
    )
    page = replace_once(page, "</head>", STYLE + "  </head>", "</head>")
    page = replace_once(
        page,
        "<h1>Decompilation Status</h1>",
        build_summary(report, stats, repo_url, commit),
        "<h1> heading",
    )
    return page, stats


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("html", type=Path, help="Report written by reccmp-reccmp --html (modified in place)")
    parser.add_argument("--repo-url", default=DEFAULT_REPO_URL, help="Repository link shown in the header")
    parser.add_argument("--commit", help="Commit SHA the report was built from")
    args = parser.parse_args()

    page = args.html.read_text(encoding="utf-8")
    page, stats = enhance(page, args.repo_url.rstrip("/"), args.commit)
    args.html.write_text(page, encoding="utf-8")

    print(
        f'Accuracy {stats["accuracy"] * 100:.2f}%, progress {stats["progress"] * 100:.2f}%, '
        f'{stats["perfect"]}/{stats["total"]} functions perfect'
    )


if __name__ == "__main__":
    main()
